---
# Staging inventory — для тестирования

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    cobbler:
      hosts:
        rasp-staging:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: root
          ansible_become: true
