---
# Production inventory — реальные хосты

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    cobbler:
      hosts:
        rasp01:
          ansible_host: 192.168.0.88
          ansible_user: root
          ansible_become: yes

# Дополнительные хосты добавляются так:
#        rasp02:
#          ansible_host: 192.168.0.89
#          ansible_user: root
#          ansible_become: yes
#          cobbler_pxe_network: "10.255.255.0/24"   # другая подсеть для этого хоста
#          cobbler_pxe_ip: "10.255.255.1/24"