---
# deploy.yml — только запуск Docker-стека (без пересборки образов)

- name: Только deploy (без пересборки)
  hosts: cobbler
  become: true
  gather_facts: false

  roles:
    - role: cobbler
      tasks_from: stack
      vars_from: stack
